### PR TITLE
A user can belong to more than one peers

### PR DESCRIPTION
**Pull request by skatsaounis**
Change model's UserProfile ForeignKey peer to M2M relationship peers. Apply change to whole FoD project. Add model PeerNotify, a table where FoD keeps record of peer notifications about their user's actions. Add missing requirements of project. Contain Data Migration to copy information from peer to peers. Fill PeerNotify with data (Asume that all peers have received notifications for all their existing users).

Pending: Foreign Key peer has to be removed from UserProfile model, after testing that FoD is functional after these changes.

### CODE REVIEW

**Comment by zmousm** [comment]
So the concept is to add a M2M field, do a data migration from the FK field and then remove the FK field? Apps are presumably updated to use the new field, right?

**Comment by skatsaounis** [comment]
This is the exact concept. Peer attribute will remain until changes will be fully tested. After that it must be removed. As far as changes are concerned, in order to update apps to use peers attribute, some issues had to be fixed. For example, at previous version, emails were sent to peers if one of their users had activated his account. At this version, a user can belong to more than one peer. So when user activates his account for another peer than his first, email must be sent to the correct peer. The decision was to keep record of already sent notifications so as not to send them again. Notice that this feature (notification table) could be useful in the future for other purposes too. In conclusion, after this update FoD can accept users belonging to many peers instead of one.

**Comment by zmousm** [comment]
How would a backwards migration work out?

**Comment by skatsaounis** [comment]
There is no need for backwards migration. That happens because now users can belong to one or more peers. As a result previous information is preserved to m2m relationship and it gets expanded with new information, if and only if a user want to be member of another peer too.

**Comment by zmousm** [comment]
It was a question of broader scope, not limited to the particular use case (specifically FoD); how (if at all) one would handle such a case, which would apparently imply data loss.

**Comment by kroustou** [comment]
Well, there is not a specific way to handle that. One case is that you can keep the pre migration data and apply them in case of a backwards migration. An other case is just selecting the first peer from the ones related (from the m2m) and apply them as foreign key. Django can't handle that in an automatic way (and as far as i know there is not a common way or suggested practice). In general south does not bother with handling data migrations.

**Pull request merged**
